version: '3'
services:
  rabbit:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
  rest:
    image: 856324650258.dkr.ecr.eu-central-1.amazonaws.com/corp-check-rest:%TAG%
    ports:
      - 3001:3000
    environment:
      - RABBITMQ_CONNECTION_URL=amqp://rabbit
      - MONGO_CONNECTION_URL=mongodb://mongo:27017
    command: npm run start:f
  worker:
    image: 856324650258.dkr.ecr.eu-central-1.amazonaws.com/corp-check-worker:%TAG%
    environment:
      - RABBIT_ENDPOINT=amqp://rabbit
      - API_URL=http://rest
  test:
    image: corp-check-test
    build: .
    environment:
      - API_URL:http://rest
