version: '3'
services:
  rabbit:
    container_name: corp-check-e2e-rabbit
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
  mongo:
    container_name: corp-check-e2e-mongo
    image: mongo:latest
    ports:
      - 27017:27017
  registry:
    container_name: corp-check-e2e-registry
    image: burkostya/npm-registry:latest
    ports:
      - 5984:5984
      - 80:80
  rest:
    container_name: corp-check-e2e-rest
    image: 856324650258.dkr.ecr.eu-central-1.amazonaws.com/corp-check-rest:%TAG%
    ports:
      - 3000:3000
    environment:
      - RABBITMQ_CONNECTION_URL=http://guest:guest@rabbit:15672
      - MONGO_CONNECTION_URL=mongodb://mongo:27017/corp-check
      - NPM_REGISTRY_URL=http://registry
    volumes:
      - "%AWS_CRED_SOURCE%:/root/.aws"
    command: npm run start:f
    depends_on:
      - rabbit
      - mongo
      - worker
  worker:
    container_name: corp-check-e2e-worker
    image: 856324650258.dkr.ecr.eu-central-1.amazonaws.com/corp-check:%TAG%
    environment:
      - RABBIT_ENDPOINT=amqp://rabbit
      - API_URL=http://rest:3000
      - NPM_CONFIG_REGISTRY=http://registry
      - NPM_COUCHDB_ENDPOINT=http://registry
      - NPM_SEARCH_ENDPOINT=http://test:3002/-/v1/search
      - QUEUE_NAME=tasks-local
    depends_on:
      - rabbit
      - registry
    restart: on-failure
  test:
    container_name: corp-check-e2e-test
    image: corp-check-test
    build: .
    ports:
      - 3002:3002
    environment:
      - NPM_CONFIG_REGISTRY=http://registry
      - API_URL=http://rest:3000
      - MONGO_URL=mongodb://mongo:27017
    depends_on:
      - registry
      - rest
